### ISSUE TITLE
Fundryu (and Gravity assemblers) aren't affected by beacons

### ISSUE THREAD

**Issue by NonZeroEagle** [Brabra94/Fundryu#3]
![image](https://github.com/user-attachments/assets/fc7f6764-cc12-48ef-a148-aec8c072922f)
Vanilla beacons and Quantum Stabilizers don't affect Fundryu or Gravity assemblers. The fundryu lists a quantum stabilizer with 4 speed 3 modules and 7 efficiency 2 modules in the beacons section yet it doesn't get a crafting speed bonus. Assembling machines are correctly affected by quantum stabilizers. Gravity assemblers are also not affected by beacons.

**Comment by NonZeroEagle** [comment]
Speed and efficiency modules can't be inserted into the buildings directly either. If this is intended behavior it should be listed somewhere that Fundryu and Gravity assemblers can't be affected by speed or efficiency modules.

**Comment by Brabra94** [comment]
Sorry for the delayed response! This is intentional, as the building would have become way too overpowered, making the game less fun to play. The current recipes are designed to provide an optimized variant for producing primary resources without making it too "cheaty." You're right that this should have been noted. That was my mistake, and I’ll make sure to fix it.

Thank you for your feedback!
